[colors.primary]
background = '#001217'
foreground = '#a5a5a5'

[colors.normal]
black = '#002831'
red = '#c44f4f'
green = '#738a05'
yellow = '#cdc097'
blue = '#7591bc'
magenta = '#ceb5eb'
cyan = '#75bc84'
white = '#eae3cb'

[colors.bright]
black = '#475b62'
red = '#bd3613'
green = '#475b62'
yellow = '#536870'
blue = '#708284'
magenta = '#5956ba'
cyan = '#819090'
white = '#fcf4dc'
